name: push-image

on:
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1
      REPO_NAME: leetcode-animefy

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${{ env.REPO_NAME }}:latest"
          docker build -t "$IMAGE_URI" ./app
          docker push "$IMAGE_URI"
